spring.application.name=leetcode-review-system
spring.datasource.url=jdbc:postgresql://localhost:5432/leetcode_review
spring.datasource.username=marilyn
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
